git update-index --assume-unchanged "Minecraft Origin Server/server.properties"
git update-index --assume-unchanged "Minecraft Origin Server/config/nucleus/commands.conf"
git update-index --assume-unchanged "Minecraft Origin Server/config/nucleus/main.conf"
git update-index --assume-unchanged "Minecraft Origin Server/config/flexiblelogin/config.conf"
git update-index --assume-unchanged "Minecraft Origin Server/config/flexiblelogin/locale.conf"
git update-index --assume-unchanged "Minecraft Origin Server/config/reccomplex.cfg"
git update-index --assume-unchanged "Minecraft Origin Server/config/battletowers.cfg"
git update-index --assume-unchanged "Minecraft Origin Server/config/cyclicmagic.cfg"